### ISSUE TITLE
Issue is Bluetooth print

### ISSUE THREAD

**Issue by ghost** [imrankst1221/Thermal-Printer-in-Android#10]
After installing APK file in my mobile, it is turning on bluetooth, but not showing available devices. It is just showing the white screen without any data

**Comment by ghost** [comment]
If you look into video in the description you can see the same behavior. It seems like the list is populated with empty elements. he clicks on top one and it connects, yours could be lower element depending on how many Bluetooth devices are available. I think its a simple fix in DevicesList class in list adapter. Will try to post fix when will have a printer available to experiment with.

**Comment by ghost** [comment]
Ok, it took a while for me to work this out. It turns out you need ACCESS_COARSE_LOCATION permission, and request it on runtime for android 6.0+ to discover devices. full answer here: https://stackoverflow.com/a/36177638

**Comment by imrankst1221** [comment]
issue solved, check it now.
