### ISSUE TITLE
Printer Hindi language does not supported. - Thermal-Printer-in-Android

### ISSUE THREAD

**Issue by vipulmantra** [imrankst1221/Thermal-Printer-in-Android#30]
How to write pragmatically support Hindi language in Thermal-Printer-in-Android printer.  have any idea ? Please let me know. 

mPrinter.printText("नमस्कार नमस्कार नमस्कार नमस्कार नमस्कार नमस्कार ");

I try this but it not working .

**Comment by ghost** [comment]
It will not work that way, I have a solution that print your hindi text in a Canvas, then convert it to a bitmap, then print it

**Comment by vipulmantra** [comment]
ok. Thanks riyasvmc
