### ISSUE TITLE
how to SET ALIGN LEFT AND SET ALIGN RIGHT in one line?

### ISSUE THREAD

**Issue by wasitaanggara** [imrankst1221/Thermal-Printer-in-Android#7]
Man, great work but i have some proble how to set align left for any word also set align right for any word in one line ?
Thankyou dude, i tried it always align right both of that words. 

Sorry for my bad english

**Comment by FaisalAriyanto** [comment]
fun autoSpacing(left: String, right: String): String {
        val total = 31
        val space = total - left.length - right.length

        var whiteSpace = " "

        var i = 0
        while (i < space) {
            whiteSpace += " "
            i++
        }

        return left + whiteSpace + right
    }
